/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 4998b685d5a589fbacb109fd24db7a67)
interface __BaseEnv_Env {
	REPLAYS: R2Bucket;
	DB: D1Database;
	ENVIRONMENT: "staging" | "production" | "development";
	MAX_REPLAY_BYTES: "16777216";
	REPLAY_URL_TTL_SECONDS: "300";
	INGEST_SECRET: string;
	REPLAY_URL_SECRET: string;
	MIGRATION_SECRET: string;
	ADMIN_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface StagingEnv {
		REPLAYS: R2Bucket;
		DB: D1Database;
		ENVIRONMENT: "staging";
		MAX_REPLAY_BYTES: "16777216";
		REPLAY_URL_TTL_SECONDS: "300";
		INGEST_SECRET: string;
		REPLAY_URL_SECRET: string;
		MIGRATION_SECRET: string;
		ADMIN_SECRET: string;
	}
	interface ProductionEnv {
		REPLAYS: R2Bucket;
		DB: D1Database;
		ENVIRONMENT: "production";
		MAX_REPLAY_BYTES: "16777216";
		REPLAY_URL_TTL_SECONDS: "300";
		INGEST_SECRET: string;
		REPLAY_URL_SECRET: string;
		MIGRATION_SECRET: string;
		ADMIN_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "MAX_REPLAY_BYTES" | "REPLAY_URL_TTL_SECONDS" | "INGEST_SECRET" | "REPLAY_URL_SECRET" | "MIGRATION_SECRET" | "ADMIN_SECRET">> {}
}
