/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: e06684fda71e9edb009e392ca441ba7c)
interface __BaseEnv_Env {
	REPLAYS: R2Bucket;
	DB: D1Database;
	ENVIRONMENT: "development";
	MAX_REPLAY_BYTES: "16777216";
	REPLAY_URL_TTL_SECONDS: "300";
	INGEST_SECRET: string;
	REPLAY_URL_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "MAX_REPLAY_BYTES" | "REPLAY_URL_TTL_SECONDS" | "INGEST_SECRET" | "REPLAY_URL_SECRET">> {}
}
