from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys

from mxt_car_props_format import LIVE_MODIFIER_STATS, STAT_NAMES, read_binary


MACHINE_SETTINGS = (0.0, 0.25, 0.5, 0.75, 1.0)
MODIFIER_LAYERS = (
    "mts",
    "quickturn",
    "no_boost",
    "manual_boost",
    "dashplate_boost",
    "stacked_boost",
)


def _number(value: float) -> str:
    return f"{value:.9g}"


def _row(cells: list[str] | tuple[str, ...]) -> str:
    return "| " + " | ".join(cells) + " |"


def _official_paths(repo_root: Path) -> list[Path]:
    return sorted((repo_root / "mxto" / "vehicle" / "asset").glob("*/*.mxt_car_props"))


def build_report(repo_root: Path) -> str:
    paths = _official_paths(repo_root)
    if not paths:
        raise RuntimeError("no official .mxt_car_props files were found")

    lines = [
        "# Official car property audit",
        "",
        "Generated by `python tools/car/report_official_car_properties.py`.",
        "The fixed sample grid is 0%, 25%, 50%, 75%, and 100% machine setting.",
        "Stat meanings, activity, direction, and gradeability come from the native",
        "`MxtCarAuthoringSession.get_stat_schema()` table rather than this report.",
        "",
        "## Inputs",
        "",
        _row(("Vehicle document", "SHA-256")),
        _row(("---", "---")),
    ]
    documents = []
    for path in paths:
        data = path.read_bytes()
        documents.append((path, read_binary(data)))
        lines.append(_row((path.relative_to(repo_root).as_posix(), hashlib.sha256(data).hexdigest())))

    for path, properties in documents:
        title = path.stem.replace("_", " ").title()
        lines.extend(("", f"## {title}", "", "### Base curves", ""))
        headings = ["Property", *(f"{setting * 100:.0f}%" for setting in MACHINE_SETTINGS)]
        lines.append(_row(tuple(headings)))
        lines.append(_row(tuple("---" for _ in headings)))
        for stat_name in STAT_NAMES:
            curve = properties.curves["base"][stat_name]
            values = [_number(curve.sample(setting)) for setting in MACHINE_SETTINGS]
            lines.append(_row(tuple([stat_name, *values])))

        lines.extend(("", "### Non-identity special states", ""))
        state_rows: list[tuple[str, ...]] = []
        for layer_name in MODIFIER_LAYERS:
            for stat_name in LIVE_MODIFIER_STATS:
                curve = properties.curves[layer_name][stat_name]
                values = tuple(curve.sample(setting) for setting in MACHINE_SETTINGS)
                if any(abs(value - 1.0) > 1.0e-6 for value in values):
                    state_rows.append((layer_name, stat_name, *(_number(value) for value in values)))
        for stat_name in LIVE_MODIFIER_STATS:
            value = properties.s_boost_overrides[stat_name]
            base_curve = properties.curves["base"][stat_name]
            if any(abs(value - base_curve.sample(setting)) > 1.0e-6 for setting in MACHINE_SETTINGS):
                state_rows.append(("s_boost", stat_name, *(_number(value) for _ in MACHINE_SETTINGS)))

        state_headings = ("State", "Property", *(f"{setting * 100:.0f}%" for setting in MACHINE_SETTINGS))
        lines.append(_row(state_headings))
        lines.append(_row(tuple("---" for _ in state_headings)))
        if state_rows:
            lines.extend(_row(row) for row in state_rows)
        else:
            lines.append(_row(("none", "all states are identity", *("-" for _ in MACHINE_SETTINGS))))

        lines.extend(("", "### Collision corners", ""))
        lines.append(_row(("Set", "Front right", "Front left", "Rear right", "Rear left")))
        lines.append(_row(("---", "---", "---", "---", "---")))
        for label, corners in (("tilt", properties.tilt_corners), ("wall", properties.wall_corners)):
            formatted = [f"({_number(x)}, {_number(y)}, {_number(z)})" for x, y, z in corners]
            lines.append(_row(tuple([label, *formatted])))

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Report deterministic samples from official car properties")
    parser.add_argument("--output", type=Path, help="write the report to this path instead of stdout")
    args = parser.parse_args()
    repo_root = Path(__file__).resolve().parents[2]
    report = build_report(repo_root)
    if args.output is None:
        sys.stdout.write(report)
    else:
        args.output.write_text(report, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
