shader_type canvas_item;

uniform sampler2D in_outline_screen_tex;

void vertex() {
	// Called for every vertex the material is visible on.
}

void fragment() {
	vec4 screen_tex = texture(in_outline_screen_tex, SCREEN_UV);
	COLOR = screen_tex;
	// Called for every pixel the material is visible on.
}

//void light() {
//	// Called for every pixel for every light affecting the CanvasItem.
//	// Uncomment to replace the default light processing function with this one.
//}
